=== antonycc/mdcms-lib/src/main/resources/map.dtd
<!-- Map DTD -->
<!-- This DTD defines key value pairs to be loaded into a java Map -->

<!-- The top level map element contains a collection of entries -->
<!ELEMENT map (entry*)>

<!-- An entry contains a single key value pair -->
<!ELEMENT entry (
	key
	,value
	) >

<!-- The key, if XML parsing control characters should be escaped using declared entities -->
<!ELEMENT key (#PCDATA)>

<!-- The value, if XML parsing control characters should be escaped using declared entities -->
<!ELEMENT value (#PCDATA)>

=== antonycc/mdcms-lib/src/test/resources/cache.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map SYSTEM "map.dtd">
<map>
   <entry>
      <key>http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd</key>
      <value>/cache/0fdf337d-ba10-4b38-8716-9ca473147c66</value>
   </entry>
   <entry>
      <key>http://www.w3.org/TR/xhtml1/DTD/xhtml-lat1.ent</key>
      <value>/cache/2fbea239-ea23-428f-92ff-4e7a84d32660</value>
   </entry>
   <entry>
      <key>http://www.w3.org/TR/xhtml1/DTD/xhtml-special.ent</key>
      <value>/cache/55e7e4de-7ee4-4d8a-a027-1d04d8b434ec</value>
   </entry>
   <entry>
      <key>http://www.w3.org/TR/xhtml1/DTD/xhtml-symbol.ent</key>
      <value>/cache/b843ba76-c4d9-46da-a2c9-84300bfefc85</value>
   </entry>
</map>

=== antonycc/mdcms-lib/utils-lib/src/test/resources/entities.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map SYSTEM "map.dtd">
<map>
   <entry>
      <key>-//W3C//ENTITIES Latin 1 for XHTML//EN</key>
      <value>http://www.w3.org/TR/xhtml1/DTD/xhtml-lat1.ent</value>
   </entry>
   <entry>
      <key>-//W3C//ENTITIES Symbols for XHTML//EN</key>
      <value>http://www.w3.org/TR/xhtml1/DTD/xhtml-symbol.ent</value>
   </entry>
   <entry>
      <key>-//W3C//ENTITIES Special for XHTML//EN</key>
      <value>http://www.w3.org/TR/xhtml1/DTD/xhtml-special.ent</value>
   </entry>
</map>
